### ISSUE TITLE
Stealph

### ISSUE THREAD

**Issue by GSLLL85** [ScRiPt1337/Stealph-botnet#1]
Good afternoon. Please tell me:
1) Is your Stealph still working?
2) What is its detectability (when executed) by antiviruses?
3) Do I need to use a cryptor?
Thanks.

**Comment by ScRiPt1337** [comment]
> Good afternoon. Please tell me:
> 
> 1. Is your Stealph still working?
> 2. What is its detectability (when executed) by antiviruses?
> 3. Do I need to use a cryptor?
>    Thanks.

It's unmaintained
